name = input("ra gqvia ?")
surname = input(" ra aris sheni gavri ?")
age = input("ramdeni wlis xar ?")
height = input("ra simagle xar ?")
location = input("sad cxovrob")
print(name +  " " + surname + " " + str(age) + " " + str(height) + " " + location)